Include generated headers instead of declaring functions on the fly.
This avoids the following kind of warning messages:

tests.c:113:20: warning: implicit declaration of function 'wmpn_add' [-Wimplicit-function-declaration]
             refc = wmpn_add (rp, ap, bp, an, bn);
                    ^~~~~~~~